### ISSUE TITLE
The opensync can't sync 

### ISSUE THREAD

**Issue by xzf16** [deependhulla/opensync#10]
I am using opensynce in my XiaoMi 9 android phone with MIUI to sync the calender in the synology calender and the calender in my cell phone through caldav.

It can be synchronized succesfully when I just add the calender caldav account, but some time later, it can't synchronize anymore, although when I try to do the synchronization manually.

After I delete the account and add the same account, it can be synchronized sucessfully also, but some time later, it will aslo fail to synchronize.

**Comment by xzf16** [comment]
Here is the debug information:
--- BEGIN DEBUG INFO ---

SOFTWARE INFORMATION
OpenSync version: 1.5.0.3-ose (145) Tue Apr 18 15:03:24 GMT+08:00 2017
Installed from: com.android.vending
JB Workaround installed: no

CONFIGURATION
Power saving disabled: no
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: granted
org.dmfs.permission.WRITE_TASKS permission: granted
System-wide synchronization: automatically
Account: floyd.xu@local.host
  Address book sync. interval: manually
  Calendar     sync. interval: 240 min
  OpenTasks    sync. interval: manually
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true

SQLITE DUMP
android_metadata
	|  locale |
	|  zh_CN |
----------
settings
	|  setting | value |
	|  logToExternalStorage | 0 |
----------
services
	|  _id | accountName | service | principal |
	|  5 | floyd.xu@local.host | carddav | http://gear-line.synology.me:4000/caldav.php/floyd.xu/ |
	|  6 | floyd.xu@local.host | caldav | http://gear-line.synology.me:4000/caldav.php/floyd.xu/ |
----------
sqlite_sequence
	|  name | seq |
	|  services | 6 |
	|  homesets | 26 |
	|  collections | 21 |
----------
homesets
	|  _id | serviceID | url |
	|  21 | 5 | http://gear-line.synology.me:4000/caldav.php/floyd.xu/ |
	|  22 | 5 | http://gear-line.synology.me:4000/caldav.php/group%3D%3Dusers/ |
	|  25 | 6 | http://gear-line.synology.me:4000/caldav.php/floyd.xu/ |
	|  26 | 6 | http://gear-line.synology.me:4000/caldav.php/group%3D%3Dusers/ |
----------
collections
	|  _id | serviceID | url | readOnly | displayName | description | color | timezone | supportsVEVENT | supportsVTODO | sync |
	|  20 | 6 | http://gear-line.synology.me:4000/caldav.php/floyd.xu/home/ | 0 | My Calendar | <null> | -1852160 | <null> | 1 | 0 | 1 |
	|  21 | 6 | http://gear-line.synology.me:4000/caldav.php/floyd.xu/home_todo/ | 0 | Inbox | <null> | <null> | <null> | 0 | 1 | 0 |
----------

SYSTEM INFORMATION
Android version: 9 (PKQ1.181121.001)
Device: Xiaomi MI 9 (cepheus)

--- END DEBUG INFO ---

I don't know what other information shall be offered.

**Comment by deependhulla** [comment]
log looks good.
as this code is based or orginal davdroid , would recommand to check Did you try https://www.davdroid.com/faq/automatic-synchronization-is-not-run-as-expected/, especially the Autostart things? This should help you a lot.

Also there forum link too.
https://forums.bitfire.at/topic/1659/davdroid-195-ose-does-not-sync-on-xiaomi4-android7/5

If you love this app, I would recommend you to support DAVdroid now Davx5 (the original app), please consider donating to DAVdroid(now Davx5) or purchasing it for latest update.

**Comment by nzurita** [comment]
I have the same problem, also on a Xiaomi Mi9. I need to restart the phone for sync to work properly. And also, it never syncs automatically, I have to sync manually always.
