### ISSUE TITLE
Opensync attemps to sync changes to readonly addressbooks

### ISSUE THREAD

**Issue by Tuharsky** [deependhulla/opensync#11]
I have successfully conected to CardDAV server, where I can see several addressbooks in OpenSync. Some of them are signed with a minus in a circle symbol, that means, that addressbook is read-only, thus the user has not ACL rights to edit records in that addressbook.

However, the Android contacts app dosen't know nor respect that. The phone user is allowed to edit even the contacts from those CardDAV addressbooks where he has no write access.

After the contact is saved, during the next synchronization the OpenSync attempts to push the changes into addressbook, that (unsurprisingly) ends up with error. Even worse, since now, every sync attempt ends up with error because the OpenSync is trying again and again to write changes to the addressbook where there is no write access. It is not always easy to get rid of the errors, it might be even neccessarry to remove the OpenSync account entirely.

Althought there is probably no way to stop Contacts app from editing the readonly contacts, OpenSync should IMO simply ignore and trash such sync tasks that tackle addressbooks where he knows there is no proper access. Or, such behaviour may be optional and managed in settings of OpenSync.

**Comment by Tuharsky** [comment]
I see, that DAV X5 has menu option for every single CardDAV addressbook that allows to switch the addressbook to read-only regime. Then it does not push edits to server.

**Comment by deependhulla** [comment]
its unfortunate I haven't got any time to take this app further as of now.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.

Now known Davdroid is know as as DAVx⁵
and its source-code available @ https://gitlab.com/bitfireAT/davx5-ose
Also Free Version (free apk) is available via F-droid you can use it on your phone.
https://f-droid.org/en/packages/at.bitfire.davdroid/

**Comment by Rbooot** [comment]
> I see, that DAV X5 has menu option for every single CardDAV addressbook that allows to switch the addressbook to read-only regime. Then it does not push edits to server.

Dear @Tuharsky i HAVE exactly the same problem. I’m curious to know if you found a solution or workaround ? Thanks.

@deependhulla thanks for this app

regards.

**Comment by Tuharsky** [comment]
Well, nothing great. I only use an addressbook that is periodically 
renewed on the server side.

Dňa 27. 4. 2021 o 23:07 Rbooot napísal(a):

**Comment by blackmore190** [comment]
Has anyone found a solution on this problem? 

regards

**Comment by blackmore190** [comment]
a reboot of my phone fixed the issue using DAVx5....
