### ISSUE TITLE
Format error?

### ISSUE THREAD

**Issue by Stirlitz-on-GIT** [deependhulla/opensync#12]
When create event on android and sync to cloud the ical file is not correct, there one line with "x":

BEGIN:VCALENDAR
VERSION:2.0
PRODID:+//IDN deependhulla.com//OpenSync/1.5.0.3-ose ical4android ical4j/2.
 x
BEGIN:VEVENT
DTSTAMP:20190808T062007Z
UID:97eb80de-c9be-40bc-8d4c-780c753a1d60
SEQUENCE:1
DTSTART;VALUE=DATE:20190808
DTEND;VALUE=DATE:20190809
SUMMARY:G.P.
LOCATION:Home office
DESCRIPTION:Home office
TRANSP:TRANSPARENT
CLASS:PUBLIC
PRIORITY:5
X-MICROSOFT-CDO-BUSYSTATUS:FREE
END:VEVENT
END:VCALENDAR

**Comment by deependhulla** [comment]
its unfortunate I haven't got any time to take this app further as of now.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.

Now known Davdroid is know as as DAVx⁵
and its source-code available @ https://gitlab.com/bitfireAT/davx5-ose
Also Free Version (free apk) is available via F-droid you can use it on your phone.
https://f-droid.org/en/packages/at.bitfire.davdroid/
