### ISSUE TITLE
Events are being shown multiple times

### ISSUE THREAD

**Issue by akraus53** [deependhulla/opensync#13]
Hi, I'm having a problem where events are being added to my Android calendar multiple times (up to 9 times). This doesn't happen always but very often. 

Operating System: Oxygen OS based on Android 9
Device: Oneplus 5T
Nextcloud Version: Can't find, sorry

![Screenshot_20191002-105115__01](https://user-images.githubusercontent.com/22496160/66030939-b754e400-e502-11e9-9a34-52a364cf2d8f.jpg)

**Comment by ax1036** [comment]
Same on
Operating System: Android 8.1
Device: Wileyfox Swift 2 Plus
Nextcloud Version: 15.0.13

**Comment by ax1036** [comment]
@akraus53 Davx^5 don't have issue (opensync is a fork of it)

-> apk: https://f-droid.org/fr/packages/at.bitfire.davdroid/

If this help you (and others)

**Comment by deependhulla** [comment]
its unfortunate I haven't got any time to take this app further as of now.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.

Now known Davdroid is know as as DAVx⁵
and its source-code available @ https://gitlab.com/bitfireAT/davx5-ose
Also Free Version (free apk) is available via F-droid you can use it on your phone.
https://f-droid.org/en/packages/at.bitfire.davdroid/
