### ISSUE TITLE
Feature: Support for TLSv1.3

### ISSUE THREAD

**Issue by Somebodyisnobody** [deependhulla/opensync#14]
TLSv1.3 seems currently not supported according to webserver's log.

**Comment by deependhulla** [comment]
its unfortunate I haven't got any time to take this app further as of now.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.

Now known Davdroid is know as as DAVx⁵.

and its source-code available @ https://gitlab.com/bitfireAT/davx5-ose
Also Free Version (free apk) is available via F-droid you can use it on your phone.
https://f-droid.org/en/packages/at.bitfire.davdroid/
