### ISSUE TITLE
HTTP RESPONSE: http/1.1 502 502

### ISSUE THREAD

**Issue by rol1** [deependhulla/opensync#16]
Hi,

one of my cellphones can't sync any more. It's a Xiaomi Redmi Note 8 Pro, my other Samsung works as expected. On the Xiaomi I see this in the log:
`...
HTTP RESPONSE:
http/1.1 502 502
cache-control: no-cache
Connection: close
Content-Length: 195
Content-Type: text/xml;charset=UTF-8
Date: Fri, 17 Jan 2020 09:10:17 GMT
Server: Apache/2

<?xml version="1.0" encoding="UTF-8" standalone="no"?><D:error xmlns:D="DAV:"><D:exception><D:class>CardDavInternalServerException</D:class><D:message>errorid:</D:message></D:exception></D:error>
...
CURRENT REMOTE RESOURCE:
https://carddav.web.de/CardDavProxy/carddav/AddressBook/xyzabc/Contact/75e7afdc-a040-435f-8b13-13f8c2e4dcef.vcf

EXCEPTION:
at.bitfire.dav4android.exception.HttpException: 502 502
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:325)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:298)
	at at.bitfire.dav4android.DavResource.put(DavResource.java:201)
	at com.deependhulla.opensync.syncadapter.SyncManager.uploadDirty(SyncManager.java:345)
	at com.deependhulla.opensync.syncadapter.SyncManager.performSync(SyncManager.java:156)
	at com.deependhulla.opensync.syncadapter.ContactsSyncAdapterService$ContactsSyncAdapter.onPerformSync(ContactsSyncAdapterService.java:67)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)

SOFTWARE INFORMATION
OpenSync version: 1.5.0.3-ose (145) Tue Apr 18 09:03:24 GMT+02:00 2017
Installed from: com.android.vending
JB Workaround installed: no

CONFIGURATION
Power saving disabled: yes
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: granted
org.dmfs.permission.WRITE_TASKS permission: granted
System-wide synchronization: automatically
Account: xxx@yyy.de
  Address book sync. interval: 60 min
  Calendar     sync. interval: 60 min
  OpenTasks    sync. interval: 60 min
  WiFi only: false
  [CardDAV] Contact group method: CATEGORIES
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true
Address book account: WEB.DE Adressbuch (xxx@yyy.de lQ)
  Main account: Account {name=xxx@yyy.de, type=deependhulla.com.davdroid}
  URL: https://carddav.web.de/CardDavProxy/carddav/AddressBook/1426871/Contact/
  Sync automatically: true

SQLITE DUMP
android_metadata
	|  locale |
	|  de_DE |
----------
settings
	|  setting | value |
----------
services
	|  _id | accountName | service | principal |
	|  1 | xxx@yyy.de | carddav | https://carddav.web.de/CardDavProxy/carddav/current-user-principal-uri |
	|  2 | xxx@yyy.de | caldav | https://kalender-bs.web.de/begenda/dav/users/86431a4c-f0b0-431b-b5fb-8b10ea76c7f7 |
----------
sqlite_sequence
	|  name | seq |
	|  services | 4 |
	|  homesets | 6 |
	|  collections | 8 |
----------
homesets
	|  _id | serviceID | url |
	|  1 | 2 | https://kalender-bs.web.de/begenda/dav/8419a39c-f0b0-431b-b5fb-8b10ea76c7f7/ |
	|  6 | 1 | https://carddav.web.de/CardDavProxy/carddav/AddressBook/1285d1/ |
----------
collections
	|  _id | serviceID | url | readOnly | displayName | description | color | timezone | supportsVEVENT | supportsVTODO | sync |
	|  1 | 2 | https://kalender-bs.web.de/begenda/dav/637839c-f0b0-431b-b234b-8b10ea76c7f7/calendar/ | 0 | Mein Kalender | <null> | <null> | <null> | 1 | 1 | 1 |
	|  2 | 2 | https://kalender-bs.web.de/begenda/dav/824d50ac-f0b0-431b-b5fb-8b55bc76c7f7/birthday/ | 0 | Geburtstage | <null> | <null> | <null> | 1 | 1 | 1 |
	|  8 | 1 | https://carddav.web.de/CardDavProxy/carddav/AddressBook/306a571/Contact/ | 0 | WEB.DE Adressbuch | WEB.DE AddressBook | <null> | <null> | <null> | <null> | 1 |
----------

SYSTEM INFORMATION
Android version: 9 (PPR1.180610.011)
Device: Xiaomi Redmi Note 8 Pro (begonia)

--- END DEBUG INFO ---`

First i thought the contact which is also mention in the log (but not quoted here) was broken, becaus i knew i edited it. But after deleting it, now another one, wich was not edited is mentioned in the log. So it might depend on the device. I know for some apps I have to adjust the power saving settings on the Xiaomi, but it was running here before.

Thanks

Roland

**Comment by deependhulla** [comment]
its unfortunate I haven't got any time to take this app further as of now.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.

Now known Davdroid is know as as DAVx⁵
and its source-code available @ https://gitlab.com/bitfireAT/davx5-ose
Also Free Version (free apk) is available via F-droid you can use it on your phone.
https://f-droid.org/en/packages/at.bitfire.davdroid/
