### ISSUE TITLE
Implement Nextcloud single sign on

### ISSUE THREAD

**Issue by jakobroehrl** [deependhulla/opensync#17]
Hi, 
thanks for this app.
It would be so awesome if you could implement Nextcloud single sign on
https://github.com/nextcloud/Android-SingleSignOn

**Comment by deependhulla** [comment]
will have to study this..as these days I dont get time to work on opensync.
yet thanks.
would suggest you to check with davx5 repo, the original creator of davdroid & opensync is fork of it. as they are more up-to-date with lots of standards & features.
