### ISSUE TITLE
Address book not visible in contacts

### ISSUE THREAD

**Issue by br0xpl** [deependhulla/opensync#18]
After latest android 11 update I cannot add new contacts to the opensync addressbook - it asks me for default account and the opensync is not visible on the list of available accounts.

**Comment by deependhulla** [comment]
you need to configure your NextCloud URL for using OpenSync for Addressbook sync.
As its seems you have latest Android 11, you can try original developers app (Opensync is a fork of it)
(for open-source apk) https://f-droid.org/en/packages/at.bitfire.davdroid/
Orginal URL for help : https://www.davx5.com/
Paid App : https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=en&gl=US

hope this helps you.

**Comment by niklasdahlheimer** [comment]
Just for the record: I tested this on a Google Pixel 4a: Indeed the accounts of _opensync_ does not show up in the contacts app while the accounts of _DAVx5_ do. So using the app from @deependhulla's link fixes the issue.
