### ISSUE TITLE
Improvement : it would be fine if the name of the calendar could be changed.

### ISSUE THREAD

**Issue by ericxuo** [deependhulla/opensync#19]
Hi,

I've added a calendar in the OpenSync application and it works fine under the Calendar application of my android phone.
The only thing I'd like to change is the name of the calendar. Its name is currently "calendrier" which is (probably) the french translation of "**calendar**" which again is the name of the calendar URL (https://xxx/users/myEmailAddress/ **calendar**).
Could it be possible to change "calendrier" to some other name ?

Regards.

Xuo.

**Comment by deependhulla** [comment]
you need to check in your server side(URL) where you created a calendar, you can change there like "Office Cal" or "Personal Cal" etc.. and it would reflect on phone via opensync too.

**Comment by ericxuo** [comment]
Hi,

Thank you for your reply.
I'll have a look to the calendar on the server side but I'm not sure I can do anything as it is my Microsoft Office calendar at work that I can access through davmail from login.microsoftonline.com/<companyName>/...

Regards.

Xuo.
