### ISSUE TITLE
set default for contacts

### ISSUE THREAD

**Issue by gstlouisgit** [deependhulla/opensync#20]
I installed opensync and I can now see my caldav or cardav account when creating a contact or cal.  I use the google calendar app and when creating a new appt I can see by default it has my caldav account set to save that appt.  great!

However in the android contacts it doesn't do this.  I have to select in the dropdown the cardav account.  I've looked around and just can't find a place to change this settings.  

Does anyone know a way I can have this set as default?  For an average user selecting from the dropdown in cumbersome.

**Comment by deependhulla** [comment]
its depends from phone to phone and Android version to version., some phone would give you option to make it default.
