### ISSUE TITLE
edit remote server settings

### ISSUE THREAD

**Issue by arnonuem** [deependhulla/opensync#21]
Hi, where can i edit the server URL once an account was created? The url changed to a toplevel domain and i cant find a way to update the cal/card dav url. I was only able change it by deleting an existing account and adding a new one. I would appreciate to be able to just change the baseURL when editing an account.

**Comment by deependhulla** [comment]
You can also try original developers app for these features 
(Opensync is a fork of it and its not actively develop by me)

(for open-source apk) https://f-droid.org/en/packages/at.bitfire.davdroid/
Original URL for help : https://www.davx5.com/

Davx5 Guide/manual (Opensync is somewhat similar but its fork of older-version )https://www.davx5.com/manual/index.html

Paid App : https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=en&gl=US
