### ISSUE TITLE
JMAP support

### ISSUE THREAD

**Issue by or29544** [deependhulla/opensync#22]
Could we please have JMAP sync support? It's a newer sync format for mail, calendars and contacts.

**Comment by deependhulla** [comment]
No Plan from my side.

You can also try original developers app for these features request. (K-9 Mail for Email too)
Also check out 	
Ltt.rs - Open Source Email client (JMAP) https://play.google.com/store/apps/details?id=rs.ltt.android&hl=en&gl=US 

While Opensync is a fork of it and its not actively develop by me for quite some time.

(for open-source apk) https://f-droid.org/en/packages/at.bitfire.davdroid/
Original URL for help : https://www.davx5.com/

Davx5 Guide/manual (Opensync is somewhat similar but its fork of older-version )https://www.davx5.com/manual/index.html

Paid App : https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=en&gl=US
