### ISSUE TITLE
Found a crash while adding a new event

### ISSUE THREAD

**Issue by cdannebe** [deependhulla/opensync#24]
Hi,
I added an appointment and during every sync opensync crashes.

[debug-opensync.txt](https://github.com/deependhulla/opensync/files/8430095/debug-opensync.txt)

Hope this helps you.

Thanks for your time spent on this application.

Regards, Christian

**Comment by deependhulla** [comment]
Sorry ,cannot identify what went wrong at your end.

While Opensync is a fork of it and its not actively develop by me for quite some time.

Would suggest to checkout for open-source apk of DAvDrod/Davx5 now on 
https://f-droid.org/en/packages/at.bitfire.davdroid/
Original URL for help : https://www.davx5.com/

Davx5 Guide/manual (Opensync is somewhat similar but its fork of older-version )https://www.davx5.com/manual/index.html

Paid App : https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=en&gl=US
