### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by iqbalridha** [deependhulla/opensync#5]
This is the proposed logo I submitted. Tell you how you think sir. If you want a change I can follow it up. Thank you.
https://steemit.com/utopian-io/@iqbalridha/logo-design-proposal-for-open-sync-app

**Comment by deependhulla** [comment]
@iqbalridha , thanks for propose, I am fine with current logo. Also your logo suggested looks alike to Ubuntu linux. so sorry rejecting the proposed logo.

have a good day.

**Comment by iqbalridha** [comment]
No problem Mr, thank you for notices
