### ISSUE TITLE
www.google.co.th.com

### ISSUE THREAD

**Issue by GALAXYver7** [deependhulla/opensync#6]
Eror app

**Comment by christianlupus** [comment]
I am sorry, I do not get your point. Could you please provide a more detailed description of your problem? 

Please provide the following information if applicable:
- What has happened?
- What should happen instead?
- Is it reproducible?
- What did you do to narrow down the problem?
- Which version of the app do you use?
- Which OS and which version are you running?
- Any more information that might be useful?

Please wait calmly and be prepared to answer further questions.
