### ISSUE TITLE
Not visible in SMS app AfW

### ISSUE THREAD

**Issue by stasiakk** [deependhulla/opensync#7]
Hi, I'm using apps, and work fine, but contacts synced with this APP (WebDAV) are not showing in SMS app.
I'm using AfW profile, and i don't know where is problem. Are someone have tested it on AfW profile?

**Comment by deependhulla** [comment]
Not tested with Android for work.:-(

**Comment by deependhulla** [comment]
Hard to tell , what issue, would suggest to  checkout original  davdroid ( now know as DAVx⁵ ), on play-store or fdroid marketplace to see if it helps you.
