### ISSUE TITLE
Duplication of calendar entries in the device only

### ISSUE THREAD

**Issue by christianlupus** [deependhulla/opensync#8]
I have the following problem:
From time t time I see that calendar entries are duplicated in my android device. Let me explain a bit more in detail.
I have a certain event in the iCal calendar. Via other clients I can verify the event is there only once. In all my android calendar apps the event is shown multiple times, e.g. twice or triple. This does by far not happen with all events and most of these are unaffected. However this is filing up my calendar if it happens with recurring events.

I made a log during a (normal) sync but I'd like to avoid posing the file in a public homepage like github. Of course I am willing to share with selected people.

Please tell me what to do to track down the problem.

--- 
I am running on Android 9. 
<details><summary>Debug information within the app.</summary>

```
SOFTWARE INFORMATION
OpenSync version: 1.5.0.3-ose (145) Tue Apr 18 09:03:24 GMT+02:00 2017
Installed from: com.android.vending
JB Workaround installed: no

CONFIGURATION
Power saving disabled: yes
android.permission.READ_CONTACTS permission: granted
android.permission.WRITE_CONTACTS permission: granted
android.permission.READ_CALENDAR permission: granted
android.permission.WRITE_CALENDAR permission: granted
org.dmfs.permission.READ_TASKS permission: granted
org.dmfs.permission.WRITE_TASKS permission: granted
System-wide synchronization: automatically
Account: me@christian-wolf.click
  Address book sync. interval: 240 min
  Calendar     sync. interval: 60 min
  OpenTasks    sync. interval: 60 min
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true
Account: c.wolf@lsr.uni-saarland.de
  Address book sync. interval: 240 min
  Calendar     sync. interval: 60 min
  OpenTasks    sync. interval: 60 min
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true
Account: c.wolf@acesomed.com
  Address book sync. interval: 240 min
  Calendar     sync. interval: 60 min
  OpenTasks    sync. interval: 60 min
  WiFi only: false
  [CardDAV] Contact group method: GROUP_VCARDS
  [CalDAV] Time range (past days): 90
           Manage calendar colors: true

...

SYSTEM INFORMATION
Android version: 9 (PKQ1.180917.001.V10.0.7.0.PDLMIXM)
Device: Xiaomi Mi A2 Lite (daisy_sprout)
```
</details>

**Comment by deependhulla** [comment]
Hard to tell , what issue, would suggest to  checkout orginal  davdroid ( now know as DAVx⁵ ), on play-store or fdroid marketplace to see if it helps you.

**Comment by christianlupus** [comment]
So, all in all you simply suggest me to use a paid version instead of your free app?

I was intending to help you track down the problem but I assume this is not the case if I use another app like DAVx5. Of course I can try the software to see if the problem persists.

**Comment by anthonymasset** [comment]
Same problem for me. Sometimes, the event is shown 3 or 4 times. It looks like it duplicates when I update the event at the server side.

**Comment by deependhulla** [comment]
its unfortunate I haven't got any time to take this app further as of now.

If you love this app, I would recommend you to support DAVdroid (the original app), please consider donating to DAVdroid or purchasing it.

Now known Davdroid is know as as DAVx⁵ 
and its source-code available @ https://gitlab.com/bitfireAT/davx5-ose
Also Free Version is available via Frdoid 
https://f-droid.org/en/packages/at.bitfire.davdroid/
