### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by WerVbn** [deependhulla/opensync#9]
At the Google Play Store, you are claiming that this App is open source, but in this repository is no source code provided related to the app. Why?

**Comment by deependhulla** [comment]
OpenSync is actually a fork of davdroid ( now know as DAVx⁵ ), when it was created with icon and few changes done to core-code for which you would see the php file, while the functionality remained the same. , thus you need to download davdroid code and need to apply my icon & run my php on same.
for old version refer there website : https://gitlab.com/bitfireAT/davx5-ose/commits/v1.5.0.3-ose
for latest version checkout https://gitlab.com/bitfireAT/davx5-ose

would highly recommend  to checkout original davdroid ( now know as DAVx⁵ ) source code.
